//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen v0.14.0. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceClass) DeepCopyInto(out *NamespaceClass) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Spec.Resources != nil {
		out.Spec.Resources = make([]ResourceTemplate, len(in.Spec.Resources))
		for i := range in.Spec.Resources {
			// deep copy RawExtension.Raw bytes if present
			out.Spec.Resources[i].Template = runtime.RawExtension{}
			if in.Spec.Resources[i].Template.Raw != nil {
				out.Spec.Resources[i].Template.Raw = make([]byte, len(in.Spec.Resources[i].Template.Raw))
				copy(out.Spec.Resources[i].Template.Raw, in.Spec.Resources[i].Template.Raw)
			}
		}
	}
	// Status is simple struct, shallow copy is fine
}

// DeepCopyObject implements runtime.Object
func (in *NamespaceClass) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(NamespaceClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for list
func (in *NamespaceClassList) DeepCopyInto(out *NamespaceClassList) {
	*out = *in
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]NamespaceClass, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

// DeepCopyObject implements runtime.Object for the list
func (in *NamespaceClassList) DeepCopyObject() runtime.Object {
	if in == nil {
		return nil
	}
	out := new(NamespaceClassList)
	in.DeepCopyInto(out)
	return out
}
